{{- include "adp-helm-library.deployment" (list . "fcp-jkr-demo-backend-node-1.deployment") -}}
{{- define "fcp-jkr-demo-backend-node-1.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "fcp-jkr-demo-backend-node-1.container") }}
{{- end -}}
